### ISSUE TITLE
RQGIS doesn't recognize SAGA

### ISSUE THREAD

**Issue by rdornas** [jannes-m/RQGIS#103]
Hi, guys! I am new to R, so excuse me in advance if I question something obvious.

I just installed RQGIS (after some trouble to make QGIS installation through homebrew in Mac OS) and following some steps from your tutorial, I realized that RQGIS doesn't recognize SAGA in `qgis_session_info()`:

> $qgis_version
> [1] "2.18.22"
> 
> $gdal
> [1] "2.1.3"
> 
> $grass6
> [1] FALSE
> 
> $grass7
> [1] "7.4.1"
> 
> $saga
> NULL

I went to terminal to try to install SAGA with `brew install saga-gis-lts`, but I got the following message:

> Warning: osgeo/osgeo4mac/saga-gis-lts 2.3.2 is already installed and up-to-date
> To reinstall 2.3.2, run `brew reinstall saga-gis-lts`

I already reinstalled but without success. RQGIS doesn't recognize SAGA in `qgis_session_info()` neither find its algorithms in `find_algorithms`.

If I can provide some other information in order to solve this problem, please tell me.

Thank you very much!

**Comment by jannes-m** [comment]
Can you please open the QGIS GUI and check if SAGA algorithms are available in the toolbox?

**Comment by pat-s** [comment]
Which QGIS version? Which macOS version? 
I don't have time today to look into it. We're both not using our macOS on a daily base so we can't steadily monitor it.
I'll take a look in the next days if the issue persists.

**Comment by rdornas** [comment]
Concerning your questions: SAGA algorithms are available in the toolbox of QGIS GUI. However, the QGIS GUI (2.18.22) shows SAGA 2.3.1 instead of 2.3.2 (which terminal recognizes as saga-gis-lts version).

I am running a macOS High Sierra version 10.13.6.

Thanks!

**Comment by pat-s** [comment]
For me the QGIS GUI shows also v2.3.2. Do you have an older installation of SAGA on your system?

Other than that, I get a different severe error not finding the `qgis.core` processing lib when calling `qgis_session_info()`.

I need to debug that first. Interesting that you do not have this problem :smile: 
For now, I cannot provide a fix here and need to discuss with @jannes-m how we proceed here.

**Comment by rdornas** [comment]
I uninstalled and reinstalled all versions of QGIS, just to be sure that no older installation could be causing this trouble.

Now in QGIS GUI, SAGA version is 2.3.2. However, `RQGIS::qgis_session_info()` still shows:

`$saga
NULL`

I've never had the `qgis.core` error you are reporting.

**Comment by pat-s** [comment]
Ok thanks. For the record, which version of `reticulate` do you have installed?

As you might know the geospatial com in R is very small and the toolset currently does not allow stable CI testing so we rely on user feedback like yours to catch errors here.

**Comment by pat-s** [comment]
Ok, for some reason it works today for me without changing anything compared to yesterday.

`qgis_session_info()` recognizes SAGA.

Can you do a `brew info saga-gis-lts`?

**Comment by rdornas** [comment]
Reticulate version: `packageVersion("reticulate")
[1] ‘1.9’`

`brew info saga-gis-lts`:

> osgeo/osgeo4mac/saga-gis-lts: stable 2.3.2 (bottled), HEAD [keg-only]
System for Automated Geoscientific Analyses - Long Term Support
http://saga-gis.org
/usr/local/Cellar/saga-gis-lts/2.3.2 (138 files, 17.8MB)
  Poured from bottle on 2018-08-01 at 03:08:47
From: https://github.com/osgeo/homebrew-osgeo4mac/blob/master/Formula/saga-gis-lts.rb
==> Dependencies
Build: automake ✔, autoconf ✔, libtool ✔
Required: gdal2 ✔, proj ✔, wxmac ✔
Recommended: unixodbc ✔, libharu ✔, qhull ✔
Optional: brewsci/science/vigra ✘, postgresql ✔, python@2 ✔, opencv ✘
==> Options
--with-app
	Build SAGA.app Package
--with-opencv
	Build with opencv support
--with-postgresql
	Build with postgresql support
--with-python@2
	Build with python@2 support
--with-vigra
	Build with vigra support
--without-libharu
	Build without libharu support
--without-qhull
	Build without qhull support
--without-unixodbc
	Build without unixodbc support
--HEAD
	Install HEAD version
==> Caveats
saga-gis-lts is keg-only, which means it was not symlinked into /usr/local,
because LTS version is specifically for working with QGIS.
If you need to have saga-gis-lts first in your PATH run:
  echo 'export PATH="/usr/local/opt/saga-gis-lts/bin:$PATH"' >> ~/.bash_profile
For compilers to find saga-gis-lts you may need to set:
  export LDFLAGS="-L/usr/local/opt/saga-gis-lts/lib"
  export CPPFLAGS="-I/usr/local/opt/saga-gis-lts/include"

**Comment by pat-s** [comment]
I checked with reticulate v1.6, v1.9 and v1.10. All work for me.

Could you please run

```r
library(RQGIS)
open_app()
```

And then in a python file in RStudio:

```python
from processing.core.Processing import Processing
Processing.initialize()
import processing
# ParameterSelection required by get_args_man.py, algoptions, alghelp
from processing.core.parameters import (
  ParameterSelection,
  ParameterRaster,
  ParameterVector,
  ParameterMultipleInput
)
from processing.gui.Postprocessing import handleAlgorithmResults
# needed for open_help
from processing.tools.help import createAlgorithmHelp
# needed for qgis_session_info
from processing.algs.saga.SagaAlgorithmProvider import SagaAlgorithmProvider
from processing.algs.saga import SagaUtils
from processing.algs.grass.GrassUtils import GrassUtils
from processing.algs.grass7.Grass7Utils import Grass7Utils
from processing.algs.otb.OTBAlgorithmProvider import OTBAlgorithmProvider
from processing.algs.otb.OTBUtils import getInstalledVersion
from processing.algs.taudem.TauDEMUtils import TauDEMUtils
from osgeo import gdal
from processing.tools.system import isWindows, isMac

SagaUtils.getSagaInstalledVersion()
```

**Comment by pat-s** [comment]
No problem, I try to be more specific:

1. In a fresh R session, please run

```r
library(RQGIS)
open_app()
```

2. Then, in RStudio, create a new Python file. Paste the python code from above, select and run it. 

This should work (at least it does for me) and I am interested if you face any error messages here. This is part of the code that is run in the background in `qgis_session_info()` to retrieve the SAGA version.

**Comment by jannes-m** [comment]
Wow, I didn't know that it is possible to run Python code directly in an R session, this is awesome. So far, I have been always using `py_run_string()` but that's not necessary which is awesome for interactive testing!

**Comment by jannes-m** [comment]
Still, I don't think it is necessary to run all the Python code since it was already executed when running `open_app()`. Hence it is maybe a bit easier for @rdornas to run:

```r
library("RQGIS")
open_app()
py_run_string("tmp = SagaUtils.getSagaInstalledVersion()")$tmp
```
This should give back the SAGA version used by QGIS in case QGIS found a working SAGA installation.
In my case this returns `"2.3.1"`.

**Comment by rdornas** [comment]
My problem is just that I've never used Python in R and I don't know how to create a Python instance in R. I'm sorry!

I just did what Jannes recommended and...:

> library("RQGIS")
Carregando pacotes exigidos: reticulate
> 
> open_app()
Checking for homebrew osgeo4mac installation on your system. 
> Found QGIS osgeo4mac installation. Setting environment...
> 
> py_run_string("tmp = SagaUtils.getSagaInstalledVersion()")$tmp
NULL

**Comment by pat-s** [comment]
@rdornas No problem ;) The python instance is already running after you've called any RQGIS function.

While debugging today I found that your problem might be solved by just running `brew link saga-gis-lts --force`. Can you please try this and test again? Thanks!

**Comment by rdornas** [comment]
Yes, Patrick!

> $qgis_version
> [1] "2.18.22"
> 
> $gdal
> [1] "2.1.3"
> 
> $grass6
> [1] FALSE
> 
> $grass7
> [1] "7.4.1"
> 
> $saga
> [1] "2.3.2"

Thank you very much, guys!!!

**Comment by pat-s** [comment]
You're welcome :tada:
