### ISSUE TITLE
GRASS7 needs to be installed after QGIS2

### ISSUE THREAD

**Issue by pat-s** [jannes-m/RQGIS#104]
(Should be added to the install guide!)

To correctly find the path to the processing plugin. Otherwise the following happens:

When installed via `homebrew`, `Grass7Utils.grassPath()` reports

```
/Applications/Grass-7.0.app/Contents/MacOS
``` 

but that path does not exist.
The GRASS installation is working fine though.

**Comment by jannes-m** [comment]
Please have a look at c43e83ac, and report back if improvements can be made.
