### ISSUE TITLE
"argument "type_name" is missing, with no default"

### ISSUE THREAD

**Issue by odgersn** [jannes-m/RQGIS#110]
I am trying to run the algorithm `grass7:r.stats` to compute area statistics for a pair of categorical rasters. It works if I supply the rasters as a list of objects in my R environment, but it doesn't work if I supply the rasters as a list of file paths.

An example that "works":
```
# Create rasters
set.seed(5)
a <- raster(nrows = 10, ncols = 10, vals = sample.int(10, size = 100, replace = T))

set.seed(5)
b <- raster(nrows = 10, ncols = 10, vals = sample.int(3, size = 100, replace = T))

# Initialise QGIS
set_env(root = "C:/Program Files/QGIS 2.18/")

# Get default parameters
p <- get_args_man(alg = "grass7:r.stats")

# Set up parameters
p$input <- list(a, b)
p$rawoutput <- "output.txt"   # Output of alg is a text file containing stats
p[["-a"]] <- "True"
p[["-c"]] <- "True"
p[["-p"]] <- "True"
p[["-1"]] <- "False"
p$separator <- "\"tab\""

# Run algorithm
out <- run_qgis(alg = "grass7:r.stats",
                params = p,
                load_output = F)
```
I say that it "works" in the sense that it completes successfully without errors. However, the output is not what I intended:

```
# Truncated contents of output.txt
1-1.035294	1-1.007843	2
1-1.035294	1.996078-2.003922	2
1-1.035294	2.992157-3	1
1.988235-2.023529	1-1.007843	1
1.988235-2.023529	1.996078-2.003922	1
1.988235-2.023529	2.992157-3	2
...
```
The output is a tab-separated text file. In this case, the first two columns are numeric ranges of values in rasters `a` and `b`, respectively. The third column is the number of cells that have the given combination of values in the first two columns.

The output is not what I intended because I want the first  two columns to contain integer values rather than ranges, since `a` and `b` are integer-valued rasters. But I get that `RQGIS` must be writing `a` and `b` to temporary raster files using a default floating-point data type, so `grass7:r.stats` treats them accordingly.

To try and control the data type, I thought I'd write `a` and `b` to raster files myself, and specify an integer data type. Then I can pass the rasters to `RQGIS` myself as file paths.

```
# Write rasters to file and try again
writeRaster(a, "a.tif", datatype = "INT2S")
writeRaster(b, "b.tif", datatype = "INT2S")
```

Test the algorithm using only one raster:
```
p$input <- "a.tif"

# Run algorithm
out <- run_qgis(alg = "grass7:r.stats",
                params = p,
                load_output = F)
```

Success!:

```
# Contents of output.txt
1	5
2	4
3	7
4	10
5	6
6	5
7	1
8	3
9	5
10	4
```

The values in the first column are the integer values in `a` and the values in the second column are their counts, just like I want. Now let's try to supply both `a` and `b` as file paths:

```
p$input <- list("a.tif", "b.tif")

# Run algorithm
out <- run_qgis(alg = "grass7:r.stats",
                params = p,
                load_output = F)
```

This doesn't work, and I get the following error message:

```
Error in type_name[i] %in% c("vector", "raster", "table") : 
  argument "type_name" is missing, with no default
```

I guess that `run_qgis` is unable to detect that both `a.tif` and `b.tif` are actually rasters. Can I specify `type_name` somewhere myself, or is this a bug? I've had no luck trying to figure out a workaround so far.

**Comment by jannes-m** [comment]
Hey,
if you are providing the paths to the raster files, you need to use QGIS syntax, i.e. `p$input = "raster1.tif;raster2.tif;raster3.tif"`. 
If you run `params = pass_args(alg = "grass7:r.stats", input = list(a, b))` and then have a look at `params$input` you'll notice that `run_qgis()` is just doing that in the background.
So, in your case:

``` r
library("raster")
#> Loading required package: sp
library("RQGIS")
#> Loading required package: reticulate
# Create rasters
set.seed(5)
a = raster(nrows = 10, ncols = 10, vals = sample.int(10, size = 100, replace = TRUE))
set.seed(5)
b = raster(nrows = 10, ncols = 10, vals = sample.int(3, size = 100, replace = TRUE))
# Write rasters to file and try again
writeRaster(a, file.path(tempdir(), "a.tif"), datatype = "INT2S")
writeRaster(b, file.path(tempdir(), "b.tif"), datatype = "INT2S")

# Set up parameters
p = get_args_man(alg = "grass7:r.stats")
#> Assuming that your root path is '/usr'!
p$input = paste(file.path(tempdir(), "a.tif"),
                file.path(tempdir(), "b.tif"), 
                sep = ";")
p$rawoutput <- "output.txt"   # Output of alg is a text file containing stats
p[["-a"]] <- "True"
p[["-c"]] <- "True"
p[["-p"]] <- "True"
p[["-1"]] <- "False"
p$separator <- "\"tab\""
# run QGIS
run_qgis(alg = "grass7:r.stats", params = p)
#> $html
#> [1] "-180,180,-90,90"
#> 
#> $rawoutput
#> [1] "/tmp/RtmpgxF1Ju/reprex1453b55c431/output.txt"
read.table("/home/rstudio/RQGIS/output.txt")
#>    V1 V2           V3 V4     V5
#> 1   1  1 6.375766e+13  5 12.82%
#> 2   2  1 4.905048e+13  4 10.26%
#> 3   3  1 6.375853e+13  7 17.95%
#> 4   4  1 2.255690e+13  3  7.69%
#> 5   4  2 7.160738e+13  7 17.95%
#> 6   5  2 5.296265e+13  6 15.38%
#> 7   6  2 5.100656e+13  5 12.82%
#> 8   7  2 4.902683e+12  1  2.56%
#> 9   8  3 3.040575e+13  3  7.69%
#> 10  9  3 4.021111e+13  5 12.82%
#> 11 10  3 5.984593e+13  4 10.26%
```

<sup>Created on 2018-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

To be honest, I am not familiar with `grass7:r.stats`, so not really sure what the function is doing when provided with two rasters. Secondly, are you familiar with `raster::freq()`, might already do what you want. Thirdly, it is a bit annoying that one has to read in the table output manually but I have to admit that I have never used **RQGIS** for computing table outputs.

**Comment by odgersn** [comment]
Thanks Jannes! I haven't had a chance to check it out yet, but that makes sense.
