### ISSUE TITLE
ERROR 4 on temporary SAGA files when RQGIS is run inside a function

### ISSUE THREAD

**Issue by odgersn** [jannes-m/RQGIS#111]
I've built a package function that employs RQGIS internally in order to automate a sequence of terrain analyses. The basic body of the function is as follows:

```
terrain <- function(root, <other arguments>) {
  
  # Set QGIS environment
  RQGIS::set_env(root = root)

  # Run a series of saga and grass7 algorithms, including saga:slopeaspectcurvature, 
  # saga:relativeheightsandslopepositions, grass7:r.fill.dir and grass7:r.topidx
  ...

}
```

I build my R package and load it. I run my `terrain` function and RQGIS saves temporary files into subdirectories of a temporary directory. The root temporary directory has a name like `processingd109a6c8b3e54eabb0bddae2a9972161`. The temporary files are not removed after the function finishes executing. Everything seems to work properly.

I run my `terrain` function a second time and it also seems to work properly. RQGIS continues to save temporary files into subdirectories of the same root temporary directory that it created the first time I ran `terrain` (I had thought that it might create a new root temporary directory and populate it instead). 

I run my `terrain` function a *third* time, and this time I get ERROR 4 when it tries to execute the saga algorithms, although it still executes the grass7 algorithms successfully before my function completes. This ERROR 4 message is associated with execution of the `saga:relativeheightsandslopepositions` algorithm:

```
ERROR 4: C:\Users\odgersn\AppData\Local\Temp\processing145fdb7b8f4841ec9f0f2a2bb7304443\dd421dd7344446888f8a8589275471fd\HO.sdat: No such file or directory
```
It's looking for a temporary file `HO.sdat` inside a temporary subdirectory that RQGIS created the third time I ran my `terrain` function. I took a look in this temporary subdirectory and the only file present was `HO.prj`. I compared the contents of this temporary subdirectory with the temporary subdirectory that RQGIS created for `HO` files from the first and second runs, and they contain `HO.mgrd`, `HO.prj`, `HO.sdat`, `HO.sdat.aux.xml` and `HO.sgrd`.

I assumed that the error has something to do with the fact that my `terrain` function sets the environment with `set_env` each time it is run even though I don't think it's strictly necessary. If, using Rstudio, I restart R (`Ctrl+Shift+F10`) and reload the package, it works fine again the first couple of times, but causes errors again on third and subsequent runs. After the restart, it saves temporary files in a new root temporary directory. Setting `new = TRUE` in the call to `set_env` in `terrain` does not solve the problem.

Am I missing something? What is the best practise for using RQGIS in package functions?

**Comment by jannes-m** [comment]
If possible, please always provide a small reproducible example illustrating your problem.
You can run SAGA geoalgorithms in your own functions via **RQGIS** as illustrated below. Use `tempfile()` to name your output objects, otherwise you might overwrite previously created output which might not be what you want.

``` r
library("RQGIS")
#> Loading required package: reticulate
library("raster")
#> Loading required package: sp

run_saga = function(dem) {
  run_qgis("saga:sagawetnessindex", DEM = dem, TWI = tempfile(fileext = ".sdat"),
           load_output = TRUE)
}

twi_1 = run_saga(RQGIS::dem)
#> Assuming that your root path is '/usr'!
#> $SLOPE
#> [1] "/tmp/processinged5b5106d71b46288fb293ec40f80d48/e8e324d983a442719c92760097aae8be/SLOPE.sdat"
#> 
#> $AREA_MOD
#> [1] "/tmp/processinged5b5106d71b46288fb293ec40f80d48/c914508785c548a399e0d7a464ed3f14/AREAMOD.sdat"
#> 
#> $TWI
#> [1] "/tmp/Rtmp9m5OpC/filee17edf48de.sdat"
#> 
#> $AREA
#> [1] "/tmp/processinged5b5106d71b46288fb293ec40f80d48/c786303ae15a447594ef644e81a9eadc/AREA.sdat"
twi_2 = run_saga(spDataLarge::nz_elev)
#> $SLOPE
#> [1] "/tmp/processinged5b5106d71b46288fb293ec40f80d48/a981f64ab6494d07bcdddf7508fd841f/SLOPE.sdat"
#> 
#> $AREA_MOD
#> [1] "/tmp/processinged5b5106d71b46288fb293ec40f80d48/37abd7238aef41b697c55ea6d4f81f3b/AREAMOD.sdat"
#> 
#> $TWI
#> [1] "/tmp/Rtmp9m5OpC/filee1761687ccc.sdat"
#> 
#> $AREA
#> [1] "/tmp/processinged5b5106d71b46288fb293ec40f80d48/5a3dbf00c62c47d0981b189966000e3f/AREA.sdat"
twi_3 = run_saga(spDataLarge::ta$elev)
#> $SLOPE
#> [1] "/tmp/processinged5b5106d71b46288fb293ec40f80d48/521afc8e9a114eed9fe4089ca3039761/SLOPE.sdat"
#> 
#> $AREA_MOD
#> [1] "/tmp/processinged5b5106d71b46288fb293ec40f80d48/50cdf05beafe48acae675bb994c12433/AREAMOD.sdat"
#> 
#> $TWI
#> [1] "/tmp/Rtmp9m5OpC/filee1716b0bf59.sdat"
#> 
#> $AREA
#> [1] "/tmp/processinged5b5106d71b46288fb293ec40f80d48/5307d485f561413d98d4cbf9355f340c/AREA.sdat"
par(mfrow = c(1, 3))
plot(twi_1)
plot(twi_2)
plot(twi_3)
```

![](https://i.imgur.com/tSXeTpn.png)

<sup>Created on 2019-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
