### ISSUE TITLE
error in accessing QGIS functionality in R 

### ISSUE THREAD

**Issue by layda23** [jannes-m/RQGIS#121]
library(reticulate)
library(RQGIS)
library(raster)
library(rgdal)
ger = getData(name = 'GADM', country = 'DEU', level = 1)
set_env(root = "C:\\Program Files\\QGIS 2.18")
find_algorithms()
Error in py_run_string_impl(code, local, convert) : 
  TypeError: 'unicode' does not have the buffer interface

**Comment by pat-s** [comment]
We do not support RQGIS anymore and do not recommend to use it. Please try RQGIS3.
