### ISSUE TITLE
Plotting only a single centroid of a region in ger

### ISSUE THREAD

**Issue by marco-vene** [jannes-m/RQGIS#15]
Hi,

Thanks for the brilliant QGIS intro.
I followed your example in plotting the centroids in the ger spatial object. My final result though does not match your image with centroids in every region, but just one centroid.

![qgis-example](https://cloud.githubusercontent.com/assets/12248653/18026066/0caa3ede-6c3c-11e6-9ea6-5ae4261a3b62.PNG)

When I run the run_qgis function I get the warining message:
running command 'batch_cmd.cmd' had status 1.
Maybe it is related.

Thanks for supporting,

Great work,

**Comment by jannes-m** [comment]
It seems you are using QGIS 2.16.1 (find out by running `qgis_session_info()`). This release has a minor bug. I explain how to fix it on https://github.com/jannes-m/RQGIS#qgis-216-modifications. To avoid the manual adjustment we recommend to use the QGIS long term release (2.14). Using the OsGeo4W-installer, you can install both the latest (2.16.1) and the long term release (2.14). In this case RQGIS will automatically use the LTR. For a detailed installation guide please refer to our package vignette (`vignette("install_guide", package = "RQGIS")`).

**Comment by marco-vene** [comment]
Thank you very much! Works!
