### ISSUE TITLE
README.md example broken for Mac

### ISSUE THREAD

**Issue by pat-s** [jannes-m/RQGIS#17]
Hi Jannes,

just came across this error message in `run_qgis` while running the README.md example:

```R
if (grepl("no features found", attr(test, "condition"))) {
   stop("The output-file ", fname, " is empty, i.e. it has no features.")
}

Error in if (grepl("no features found", attr(test, "condition"))) { : 
  Argument has length 0
```

If I comment these lines out, `run_qgis` executes properly.  
I debugged the code up to these lines and found not attribute called "condition" in the tmp file `test`. That causes the `length 0` error. 

**What interesting:** Debugging in Windows causes the same error at this point. However, running `run_qgis` as a function does NOT produce the error in Windows, only for Mac. 

Can we rewrite this check to avoid such problems? For now, I just commented the lines out. 

QGIS 2.14.7 (Kyngchaos) Mac

**Comment by jannes-m** [comment]
Hi Patrick,

thanks for detecting this bug! The if-condition was simply missing a further condition:

https://github.com/jannes-m/RQGIS/blob/ecc8a2cb3b5bb0596d0a6e385a9b45d1fe10f7d1/R/processing.R#L891-L893

`run_qgis`  and its `load_output` argument should now work properly. Ok, one more thing is still missing. If the output is neither a vector nor a raster, then the function will produce an error but I think we can leave this until this actually happens...
