### ISSUE TITLE
Add unit testing for functions

### ISSUE THREAD

**Issue by pat-s** [jannes-m/RQGIS#20]
We should set up unit testing to easen up future debugging - especially for code chunks which might be affected by QGIS version changes.

You probably have read Hadleys book chapter about unit testing using the `testthat` package: 
http://r-pkgs.had.co.nz/tests.html

The test checks can be automated using codecov (https://codecov.io) during the Travis CI checks.

**Comment by jannes-m** [comment]
You are perfectly right, we should do that!
