### ISSUE TITLE
Problem with PYTHONPATH on MacOS with Homebrew Python

### ISSUE THREAD

**Issue by eivindhammers** [jannes-m/RQGIS#25]
RQGIS functions will not run out-of-the-box with Homebrew Python 2.7.13 (I get "ImportError: No module named sip"). I have to manually add the following to `build_cmds()` in line 58/59 of helper_funs.R:

`":/usr/local/lib/qt-4/python2.7/site-packages:/usr/local/lib/python2.7/site-packages"`

Adding the same paths to `$PYTHONPATH` in ~/.bashrc and then appending a `":$PYTHONPATH"` to line 59 of helper_funs.R does not work.

**Comment by pat-s** [comment]
Custom Python interpreters beside the one of QGIS and the systems built-in one (`/usr/bin/python`) are not used at all for any processing in RQGIS.

```R
# append pythonpath to import qgis.core etc. packages
        paste0("export PYTHONPATH=", qgis_env$root, 
               "/Contents/Resources/python/"),
```

appends the QGIS python modules to `PYTHONPATH`. Afterwards, `batch_cmd.sh` calls `py_cmd.py`  in the background using the system built-in Python interpreter `/usr/bin/python` on macOS. 

Hence I do not fully understand the problem. Can you clarify on it and provide information on your OS and QGIS version?

**Comment by eivindhammers** [comment]
I use MacOS Sierra and QGIS 2.18.2 (but the problem reproduces with qgis2-ltr as well). My initial problem was that some Python modules failed to load (see example below). 

I built QGIS with `brew install qgis2` (not cask), which installs its dependencies with brew (e.g. sip-qt4). I figured my problem had to do with system python not working well with this installation of QGIS, so I replaced `/usr/bin/python` with `/usr/local/bin/python` in helper_funs.R, and appended ":/usr/local/lib/qt-4/python2.7/site-packages:/usr/local/lib/python2.7/site-packages" to my $PYTHONPATH. But it didn't work until I added the same paths to the `build_cmds()` function.

Example, running `get_args_man(alg = "qgis:intersection")`:

```R
Traceback (most recent call last):
  File "py_cmd.py", line 3, in <module>
    from qgis.core import *
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/Resources/python/qgis/__init__.py", line 26, in <module>
    from qgis.PyQt import QtCore
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/Resources/python/qgis/PyQt/QtCore.py", line 26, in <module>
    import sip
ImportError: No module named sip
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: running command 'sh batch_cmd.sh' had status 1 
2: In file(file, "rt") :
  cannot open file '/var/folders/h9/ff8dc2w1217d7lbs596phy6w0000gn/T//RtmpMDjs0m/output.csv': No such file or directory```

**Comment by pat-s** [comment]
Thanks for sharing your information. There are known issues when using `brew install qgis2` to install QGIS. That´s why we suggest to use `brew cask install qgis`.  The latter uses the kyngchaos version of QGIS. With that approach everything is working fine. 

There are several options to install QGIS using homebrew (tap `osgeo4mac`, `qgis2`, `cask/qgis`) and all differ slightly. As we cannot guarantee support for all these fast changing homebrew casks we recommend to use the one suggested in the installation vignette (which is `brew cask install qgis`). 

It is for sure possible to get other QGIS homebrew installations running (like you did) by modifying certain core files. However such core modifications prevent you (and others) from updating RQGIS then (as updating would overwrite your core changes again).

**Comment by eivindhammers** [comment]
Thanks for clarification.
