### ISSUE TITLE
execute_cmds(): rewrite in in such a way, that further python commands can be added

### ISSUE THREAD

**Issue by pat-s** [jannes-m/RQGIS#29]
We should rewrite `execute_cmds()` so that it can also be used with `qgis_session_info()`, `open_help()` and `get_args_man()`. This would delete rendundancy and make the code more consistent. In this case, we could have had rewritten the python `py_cmd.py` to `paste("python", file.path(tmp_dir), "py_cmd.py")`) in `execute_cmds()`

**Comment by jannes-m** [comment]
This improvement is no longer necessary since we are in the process of "reticulating` RQGIS.
