### ISSUE TITLE
Problem with temp. folders in `run_qgis()`

### ISSUE THREAD

**Issue by pat-s** [jannes-m/RQGIS#31]
sometimes RQGIS gets confused with working and temporary folders (`run_qgis`).
E.g., Manuel Spinolas `v.split.length` example. Link?

**Comment by pat-s** [comment]
Probably deprecated due to the `reticulate` rewrite - at least no problems with temp. folders were reported lately.

**Comment by jannes-m** [comment]
`run_qgis` now makes sure to save all outputs to the temporary folder if the user only has specified a filename, e.g., `slope.asc`, but not a full path, e.g., `D:/slope.asc` (see a4d345f).
