### ISSUE TITLE
Write "RQGIS usage" vignette

### ISSUE THREAD

**Issue by pat-s** [jannes-m/RQGIS#33]

**Comment by nuest** [comment]
Cool package you have here @pat-s @jannes-m 

I don't want to hijack this thread, but in case you're starting work on a vignette that would be a great demo case for our little research project, where we try to package the runtime environment of an analysis, see [http://o2r.info/almost/](http://o2r.info/almost/).

_Or do you have any (journal) papers that are based on an analysis with RQGIS (and are open access)?_

**Comment by jannes-m** [comment]
Thanks! Our RQGIS paper is currently in the review process of an open access journal. If it gets published (hopefully soon), we'll let you know!

**Comment by jannes-m** [comment]
Please have also a look at the RSAGA vignette (`vignette("RSAGA-landslides", package = "RSAGA")`). Are you looking for something like this?

**Comment by nuest** [comment]
Great to hear about the paper. It would be great if you can mention that here... or just make it your vignette if it is open access :-).

Thanks also for the pointer to the RSAGA vignette. Yes, that would be a nice demo, too, and I'll put it on our list.

Your README actually is a good start and from the technology perspective there is not difference between it and a "real" article, but a properly peer reviewed article is more valuable for our demos.

**Comment by jannes-m** [comment]
Unfortunately, we have to submit our paper to another journal. Before doing so, we are rewriting RQGIS in large parts. We are now using reticulate to establish a Python `tunnel`. We also strive to make RQGIS more user-friendly. Hence, it will be a while until our paper gets published...

**Comment by pat-s** [comment]
@jannes-m @nuest I personally like the concept of http://o2r.info. Jannes, we should discuss if we want to put our paper there once we get to this point.

**Comment by jannes-m** [comment]
closed with: https://rjournal.github.io/archive/2017/RJ-2017-067/index.html
