### ISSUE TITLE
QGIS installation check during RQGIS installation

### ISSUE THREAD

**Issue by pat-s** [jannes-m/RQGIS#38]
Right now, RQGIS does not work with all QGIS installation methods (e.g. `brew install qgis2` on macOS).

Two options:
1. If other installation approaches are used than specified in the `install_guide` vignette, throw `ERROR` and provide link to `install_guide` vignette. 
2. Solve problems of problematic QGIS installation methods

(1) Should be preferred as long as (2) is not solved -> Stability > Convenience

#### Mac
- [ ] Solve RQGIS problems when QGIS is installed via `brew install qgis2`
- [ ] Check if QGIS was installed using  `brew cask install qgis`

#### Windows
- [ ] OSGEO4W

#### Linux

**Comment by ebeverly** [comment]
I installed QGIS using your install guide and homebrew, but I'm still having issues in RQGIS. I keep getting this error about the QSqlDatabase.

> find_algorithms(search_term = "polygon centroid",
+                 qgis_env = my_env)
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers: 
QSqlQuery::prepare: database not open
Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
[1] "ERROR: Opening of authentication db FAILED"                                 
[2] "WARNING: Auth db query exec() FAILED"                                       
[3] "Polygon centroids------------------------------------>qgis:polygoncentroids"
[4] "Polygon centroids------------------------------------>saga:polygoncentroids"

**Comment by pat-s** [comment]
> Failed CDLL(/opt/local/lib/libgeos_c.dylib)

This error indicated that library `geos` is missing on your system. Simply call `brew install geos`.

> QSqlDatabase: QSQLITE driver not loaded
> QSqlDatabase: available drivers:
> QSqlQuery::prepare: database not open
> 
> [1] "ERROR: Opening of authentication db FAILED"
> [2] "WARNING: Auth db query exec() FAILED

These errors relate to the Kyngchaos QGIS installation for Mac and do not affect RQGIS usage (although one might thinks so since `ERROR` is stated there). 
Since last week, [`osgeo4mac`](https://github.com/OSGeo/homebrew-osgeo4mac) homebrew formulas are also supported. These QGIS installations do not throw these errors. You might want to install QGIS from there if you are annoyed by the error messages. 

I will update the vignette in the next days :)

**Comment by pat-s** [comment]
RQGIS now supports both `homebrew` and Kyngchaos QGIS installations on Mac. Also, due to the rewrite with `reticulate` this issue is deprecated.
