### ISSUE TITLE
run_qgis(): sf test not working

### ISSUE THREAD

**Issue by pat-s** [jannes-m/RQGIS#50]
@eivindhammers

When running `run_qgis()` test for your `sf` implementation, I get the following error:

```
ERROR 4: `c(0, 0)list(list(c(0, 0, 1, 1, 0, 0, 1, 1, 0, 0)), list(c(2, 2, 3, 3, 2, 2, 3, 3, 2, 2)))' not recognized as a supported file format.

Wrong parameter value: c(0, 0)list(list(c(0, 0, 1, 1, 0, 0, 1, 1, 0, 0)), list(c(2, 2, 3, 3, 2, 2, 3, 3, 2, 2)))
Error in FUN(X[[i]], ...) : 
  Unfortunately, QGIS did not produce: /var/folders/5j/_1ts10x512sg_5q_3kzc_c1w0000gn/T//Rtmp55k8FL/coords.shp
In addition: Warning message:
In if (tmp == "RasterLayer") { :
  the condition has length > 1 and only the first element will be used
```

Haven't tried to debug yet - maybe you know what's going on and can fix it quickly?

**Comment by eivindhammers** [comment]
You get that error because `run_qgis` doesn't pick up that you provided an `sf` class object, so it just passed the object as-is without exporting to shapefile. Can you post class(sf-object)?

**Comment by pat-s** [comment]
In your `sf` test in `tests/testthat/test-run-qgis.R`

```
# Convert to SF
polys <- st_as_sf(polys)

class(polys)
[1] "sf"         "data.frame"
```

Feel free to fix the issue in your fork and open a PR with a fix :)

**Comment by eivindhammers** [comment]
I just ran the `sf` test again on the `dev` branch, and can't reproduce this error. It's hard to know how to provide a fix. Perhaps a stupid question, but you're certain that you built the correct RQGIS before testing?

**Comment by pat-s** [comment]
I checked again. After building it still errored. Restarted RStudio, rebuilt `dev` and now it works. Idk what was was wrong. :smiley: Maybe some package loading interferences..

Thanks again for your contribution to RQGIS! @eivindhammers
