### ISSUE TITLE
Error in run_qgis(alg = "grass:r.slope.aspect"... : Wrong parameter value: None

### ISSUE THREAD

**Issue by thengl** [jannes-m/RQGIS#52]
I am trying to run some calculus using RQGIS and calling GRASS functions, but I am getting some errors (it could be an install problem although my GRASS 7 seems to work fine):

```
> data(dem)
> find_algorithms(search_term = "slope")
Assuming that your root path is '/usr'!
 [1] "D-Infinity Upslope Dependence------------------------>taudem:dinfinityupslopedependence"                                                                                 
...
[20] "r.slope.aspect - Generates raster layers of slope, aspect, curvatures and partial derivatives from a elevation raster layer.--->grass:r.slope.aspect"                    
> params <- get_args_man(alg = "grass:r.slope.aspect")
Assuming that your root path is '/usr'!
> params$elevation = dem
> params$slope <- "slope.asc"
> params$aspect <- "aspect.asc"
> out2 <- run_qgis(alg = "grass:r.slope.aspect", params = params, load_output = params$slope)
Assuming that your root path is '/usr'!
Error in run_qgis(alg = "grass:r.slope.aspect", params = params, load_output = params$slope) : 
  Error: Wrong parameter value: None
```

Some of the main reasons for me to use RQGIS is to be able to access GRASS GIS functions without starting up GRASS. My session info is:

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

other attached packages:
[1] rgdal_1.1-10         raster_2.5-8         RQGIS_0.2.0.9000    
[4] GSIF_0.5-3           sp_1.2-3             RevoUtilsMath_10.0.0
```

Thank you!

**Comment by jannes-m** [comment]
Hi Tom,

thank you for using RQGIS!  The error message tells you that QGIS is expecting a function argument which you have not specified. I would suggest to make use of the `options`-argument in `get_args_man`. Setting it to `TRUE` makes sure to collect all default values (if there are any):


    library("RQGIS")
    qgis_env <- set_env()  
    # attach data
    data("dem")
    params <- get_args_man(alg = "grass7:r.slope.aspect", options = TRUE,
                           qgis_env = qgis_env)

Next let's specify the function arguments:

    params$elevation <- dem
    params$slope <- file.path(tempdir(), "slope.asc")
    params$aspect <- file.path(tempdir(), "aspect.asc")
    
And finally, if you would like to import the QGIS-output directly back into R again, use a vector specifying the files you would like to import. In this case this will return a list of length 2 each containing a raster-object:


    out <- run_qgis("grass7:r.slope.aspect", params = params, 
                    qgis_env = qgis_env,
                    load_output = c(params$slope, params$aspect))

**Comment by jannes-m** [comment]
Please note also that there appears to be some problem using QGIS 2.18.4 (the latest QGIS release) with GRASS 7.2:

http://gis.stackexchange.com/questions/225464/cannot-run-grass-algorithms-in-qgis-2-18-on-ubuntu-16-04

In general, I have to admit we would rather suggest to use the LTR of QGIS (2.14) since it is much more stable.

**Comment by jannes-m** [comment]
Ok, somebody from our spring school is using QGIS 2.18.4 with GRASS 7.2 under Linux. Setting a [soft link](https://lists.osgeo.org/pipermail/qgis-user/2017-January/038907.html) will solve the problem:

    sudo ln -s /usr/bin/grass72 /usr/bin/grass70

**Comment by thengl** [comment]
Softlinking does the trick. Thanks. Maybe add in the `run_qgis` function a check that address of the various libraries is known?

**Comment by jannes-m** [comment]
We now check in `qgis_session_info` which GRASS installations can be found on your system (branch rPython). We use `qgis_session_info` in `run_qgis`, and issue a warning if the user is using GRASS72.
