### ISSUE TITLE
Opening maps produced using RQGIS in QGIS using command line (link to PyQGIS package)

### ISSUE THREAD

**Issue by thengl** [jannes-m/RQGIS#53]
What could be especially useful to have in the RQGIS is a functionality to load/display layers directly from R to QGIS. I think this is already possible via the [PyQGIS package](http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/loadlayer.html), so it should probably not be too much of effort to make functions to add raster / vector layers to an existing display. Just an idea for future enhancements.

At the moment I usually use plotKML and/or the [leaflet package](http://gsif.isric.org/doku.php/wiki:soil_webmaps#leaflet_package) to display maps directly from R.

**Comment by jannes-m** [comment]
You are perfectly right. Barry Rowlingson has worked along these lines:

https://gitlab.com/b-rowlingson/pqgisr

However, his approach only worked for UNIX-based systems (which should be fine for you :)). Have you also checked out the [mapview-package](https://github.com/environmentalinformatics-marburg/mapview) (which also uses leaflet in the background)? It's really great for fast and interactive spatial data visualization. So I wasn't sure if the PyQGIS approach is really necessary. But of course, we can think about it.

**Comment by jannes-m** [comment]
Currently, we are having a deeper look into the reticulate package. It seems that it'll work in conjunction with RQGIS. Using this package we could build on Barry's approach to do the same thing under Windows as well. I also briefly discussed with @tim-salabim the possibility of adding such a possibility to the  mapview-package.

**Comment by tim-salabim** [comment]
FWIW, I'd be more than happy to integrate QGIS map canvas into mapview provided we have some package providing the functionality. I won't be able to develop anything from within mapview itself.
