### ISSUE TITLE
Inconsistent "intern = TRUE/FALSE" in execute_cmds

### ISSUE THREAD

**Issue by eivindhammers** [jannes-m/RQGIS#56]
`execute_cmds()` has `intern = FALSE` as default, which is switched to `TRUE` when run on Darwin/Linux. However, in the actual calls to this function there are sometimes `ifelse()` statements that set `intern = FALSE` if system is Darwin. This seems both inconsistent and redundant. I guess it's enough to have the if/else in `execute_cmds()` definition? 

https://github.com/jannes-m/RQGIS/blob/a7b5993ca4cf221778f30ccd0bee1e6171a884a8/R/helper_funs.R#L124

https://github.com/jannes-m/RQGIS/blob/a7b5993ca4cf221778f30ccd0bee1e6171a884a8/R/processing.R#L300

https://github.com/jannes-m/RQGIS/blob/a7b5993ca4cf221778f30ccd0bee1e6171a884a8/R/processing.R#L916

https://github.com/jannes-m/RQGIS/blob/a7b5993ca4cf221778f30ccd0bee1e6171a884a8/R/processing.R#L293

**Comment by jannes-m** [comment]
You might be right. However, since we are completely overhauling RQGIS using the reticulate package (major update), I think, it is not worth the effort to rewrite `execute_cmds` since it is no longer necessary when using reticulate.
