### ISSUE TITLE
How to pass run_qgis() function arguments?

### ISSUE THREAD

**Issue by pat-s** [jannes-m/RQGIS#58]
Option 1: Arg `params` (list) + arg `...` (single function arguments)

Option 2: Arg `...` which can take a list OR single function arguments

**Comment by tim-salabim** [comment]
I'd generally opt for Option 2 which would make things easier for algorithms that only need 1 argument (if there are nay), but be aware that the arguments passed to `...` need to named! So you would/should test for a named list anyway.

**Comment by pat-s** [comment]
@tim-salabim yes, good point with the naming of functions passed to `...` and the ease for functions with only 1 argument.
Args should be named in any case because every QGIS function has different arguments/orders.

**Comment by jannes-m** [comment]
Consistent with Tim's recommendation, the guys from `rgrass7` have given the user the choice to either specify R named argument or a parameter-argument list. Hence, I have implemented it this way for `RQGIS`.

**Comment by pat-s** [comment]
implemented with 78af410408b0144cb1f6b26b02828fbdeaae712c
