### ISSUE TITLE
Function idea - a qgis style file creator (.qml)

### ISSUE THREAD

**Issue by Nowosad** [jannes-m/RQGIS#70]
@jannes-m Have you thought about adding some additional functions to this package? My idea is to have a function in R, where you specify a spatial vector data and could add a style to it (grouping column, color palette, etc.). 
I've already have a very limited code for adding a fill color to polygons and could share it if you want.

**Comment by jannes-m** [comment]
Thanks for your offer! Of course, I would like to have a look at your code! And then you would like to use this qml-file after opening QGIS, right? Or do you have more in mind to use the QGIS map canvas from within R (see e.g. https://gitlab.com/b-rowlingson/pqgisr)? This is possible but might also produce some problems according to Barry Rowlingson. Please refer also to issues #53, #57 for similar discussions.

**Comment by Nowosad** [comment]
@jannes-m take a look at this code - https://gist.github.com/Nowosad/44c63aea71cc2fc483331b5b4630c205 

There you have a raw code and example. When you open the `nc.gpkg` file in QGIS you should get grouped random colors. This code could be extended:
- not only random colors
- lines and opacity modifications
- etc.

**Comment by jannes-m** [comment]
@Nowosad Your idea was great! Actually, Kevin Stadtler has implemented similar functionality in his [qgisremote](https://qgisapi.gitlab.io/qgisremote/) package.
Specifically, have a look at the [renderer functions](https://qgisapi.gitlab.io/qgisremote/articles/renderers.html).

**Comment by Nowosad** [comment]
Nice! I'll look at it in the future.
