### ISSUE TITLE
ERROR in open_app() after using pacman::p_load("RQGIS") without reticulate?

### ISSUE THREAD

**Issue by raff-k** [jannes-m/RQGIS#86]
Dear RQGIS team,
by executing the following ...
`pacman::p_load("RQGIS")`
`RQGIS::set_env()`
`RQGIS::open_app()`

... I got the following error:
> Error in py_run_string_impl(code, local, convert) : 
  ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
Detailed traceback: 
  File "<string>", line 1, in <module>
  File "C:\OSGeo4W64\apps\qgis\python\qgis\__init__.py", line 27, in <module>
    from qgis.core import QgsFeature, QgsGeometry
  File "C:\OSGeo4W64\apps\qgis\python\qgis\core\__init__.py", line 30, in <module>
    from qgis._core import *

However, when I use instead
`pacman::p_load("RQGIS", "reticulate")`
`RQGIS::set_env()`
`RQGIS::open_app()`
... it works, but only when I am restarting the session.  It is not a big thing, I just want to inform you that I got some errors.

I use RQGIS_1.0.2  and  reticulate_1.2 at the moment.

**Comment by pat-s** [comment]
Seems that `pacman::p_load()` does not load `reticulate` as a dependency in your case? However, for me it does.
Could you please verify this in your `devtools::sessionInfo("RQGIS")` or by using `library()`?

PS: No need calling `set_env()` explicitly. It will be called by `open_app()` anyways.

**Comment by raff-k** [comment]
Using `devtools::session_info("RQGIS")`
I got the information ...
>... 
RQGIS        1.0.2    2017-11-04 CRAN (R 3.4.2)
reticulate   1.2      2017-09-27 CRAN (R 3.4.2)
...

I also reinstalled Pacman (pacman_0.4.6). Same error message. Using `library("RQGIS")` instead, _reticulate_ gets loaded.

**Comment by jannes-m** [comment]
I can't reproduce the error on my computer:

```r
p_load("RQGIS")
find_algorithms("catchment")
```
This works. I think the simplest solution is to just avoid `p_load()`. Though I really don't understand why **reticulate** is not loaded in your case, since it is automatically loaded when attaching **RQGIS**. And this is exactly what `p_load()` is doing, in the background it simply calls `require()`.

**Comment by raff-k** [comment]
... also strange is the following. When the error occured the first time, and I re-open a session, it re-occurs, even when I use...
`library("RQGIS", "reticulate") RQGIS::open_app()`  or `library("RQGIS") RQGIS::open_app()` then I get the same error message as mentioned above.

After the third or fourth re-opening it starts working again. But I do not really see any regularity in the behavior. Only, that I can avoid the error when I execute `open_app()` before calling other packages.

But, can you reproduce the error using following commands in a completly new session?

`pacman::p_load("raster", "data.table")`
`library("RQGIS")`
> Lade nötiges Paket: reticulate
> Warning messages:
> 1: Paket ‘RQGIS’ wurde unter R Version 3.4.2 erstellt 
> 2: Paket ‘reticulate’ wurde unter R Version 3.4.2 erstellt 

`open_app()`
>Trying to find QGIS in C:/OSGEO4~1.
Error in py_run_string_impl(code, local, convert) : 
  ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
Detailed traceback: 
  File "<string>", line 1, in <module>
  File "C:\OSGeo4W64\apps\qgis\python\qgis\__init__.py", line 27, in <module>
    from qgis.core import QgsFeature, QgsGeometry
  File "C:\OSGeo4W64\apps\qgis\python\qgis\core\__init__.py", line 30, in <module>
    from qgis._core import *

**Comment by jannes-m** [comment]
Can't reproduce it on my computer.  Next time you are in Jena, let's have a look together at your computer, ok?
