### ISSUE TITLE
Deterministic order of parameters in function call?

### ISSUE THREAD

**Issue by raff-k** [jannes-m/RQGIS#87]
Dear RQGIS-team,

I am just wondering if there is a deterministic order how the function parameter have to be set in the function. - If there is, maybe you could mention that in the description somewhere (and if you already did, I am sorry for my nescience).

Computing...
`data(dem)`
`RQGIS::run_qgis(alg = "saga:gridbuffer", FEATURES = dem, BUFFER = "tmpBuf.sdat", BUFFERTYPE = "1", DIST = "1", load_output = TRUE)`
... I got:
> Error in pass_args(alg, ..., params = params, qgis_env = qgis_env) : 
  Invalid argument value 'C:/Users/USER/AppData/Local/Temp/RtmpI9zYec/1' for parameter 'DIST'

But ...
`RQGIS::run_qgis(alg = "saga:gridbuffer", FEATURES = dem, DIST = "1", BUFFERTYPE = "1", BUFFER = "tmpBuf.sdat", load_output = TRUE)`
... works fine :-)

**Comment by jannes-m** [comment]
Interesting, shouldn't be that way... will take care of this tomorrow. Thanks for noting!

**Comment by jannes-m** [comment]
Commit https://github.com/jannes-m/RQGIS/commit/45aef93c22107b2f34ee5ce4aa16cec485fc9489 should fix your issue. However, it works only with QGIS 2.14. QGIS 2.18 only produces a prj-output file. Well, another QGIS issue, will add it to our list.
