### ISSUE TITLE
Errors arising when trying to use files on network as function inputs

### ISSUE THREAD

**Issue by susanatfybr** [jannes-m/RQGIS#88]
Hello RQGIS team!

I'm having some trouble with file path formatting to files on a network on windows. This is a new issue, as the same inputs were working without error as recently as last week.

the code:

`inDSM <- "C:/Users/Susan/Desktop/DSM.tif"
outHillshade <- "C:/Users/Susan/Desktop/Hillshade.tif"
RQGIS::run_qgis(alg="gdalogr:hillshade", INPUT = inDSM, OUTPUT = outHillshade)`

is working fine, however if inDSM is replaced with either of the following:

`inDSM <- "\\\\NetworkName\\z\\RawData\\DSM.tif"
inDSM <- "//NetworkName/z/RawData/DSM.tif"`

I'm getting the following error:

> ERROR 4: `\NetworkName/z/RawData/DSM.tif' does not exist in the file system, and is not recognized as a supported dataset name.
> Error in RQGIS::run_qgis(alg = "gdalogr:hillshade", INPUT = inDSM, OUTPUT = outHillshade) : 
>   Unable to execute algorithm
> Wrong parameter value: \NetworkName/z/RawData/DSM.tif

It seems that no matter what is input before "NetworkName" I can't get the function to register a double forward slash and recognize the file.  I'm have the exact same issue running alg="grass7:v.drape" as well.

Any help would be great. Thanks!

Using RQGIS_1.0.2

**Comment by pat-s** [comment]
Hi  @susanatfybr, thanks for contributing!

@jannes-m will take a look soon as he is in charge of all the slash/backward-slash issues on windows :)

**Comment by susanatfybr** [comment]
Sounds great, thank you!

**Comment by jannes-m** [comment]
735e856 should solve your problem. Pls give it a try (`devtools::install_github("jannes-m/RQGIS")`), and thanks for reporting back!

**Comment by susanatfybr** [comment]
this worked! thank you.
