### ISSUE TITLE
Extent mismatch between SAGA through (1) RQGIS and (2) RSAGA (but RSAGA matches the input)

### ISSUE THREAD

**Issue by raff-k** [jannes-m/RQGIS#89]
Dear RQGIS-team,

I was trying to perform a raster::overlay() using the result of a SAGA buffering algorithm through RQGIS. But, I received an error that the extent is not matching. However, using SAGA buffer through RSAGA with the same SAGA version the extent is similar to the input.
I speculate that the mismatch through RQGIS could arise by writing out SAGA-files (.sgrd/.sdat) using .tif or importing them as .tif or even .sdat (?). E.g. I got some messages that a transformation is automatically done when importing files into SAGA using .sdat or .tif files. But, with the same file using .sgrd there was no transformation.

I hope you can reproduce the following lines by copy-and-pasting:

```r
# load libraries and data
library("RQGIS", "raster", "RSAGA")
RQGIS::open_app()
env.rsaga <- RSAGA::rsaga.env(path = "C:/OSGeo4W64/apps/saga") # "2.1.2"

dem <- RQGIS::dem
slope <- RQGIS::run_qgis(alg  = "grass7:r.slope.aspect", elevation = dem, slope = "slope.tif", load_output = TRUE)
slp.s <- raster::calc(slope, fun = function(x){ifelse(x >= 20, 1, NA)}) # sub-selection of slope


# (1) buffering using SAGA through RQGIS
slp.sBuf.RQGIS <- RQGIS::run_qgis(alg = "saga:gridbuffer", FEATURES = slp.s, DIST = "1", BUFFERTYPE = "1", BUFFER = "tmpBufRQGIS.tif",  load_output = TRUE, show_output_paths = FALSE)

# (2) buffering using SAGA through RSAGA
# write files
slp.sPath <- paste0(tempdir(), "/", "SlpSOut.sgrd")
raster::writeRaster(x = slp.s, filename = slp.sPath, overwrite = TRUE, NAflag = -99999)
slp.sBuf.SAGA.path <- paste0(tempdir(),"/", "tmpBufSAGA.sgrd")

RSAGA::rsaga.geoprocessor(lib="grid_tools", module = 8, env = env.rsaga, show.output.on.console = TRUE, param = list( FEATURES = slp.sPath, BUFFER = slp.sBuf.SAGA.path , DIST = "1", BUFFERTYPE = "1"))

slp.sBuf.RSAGA <- raster::raster(paste0(tools::file_path_sans_ext(slp.sBuf.SAGA.path), ".sdat"))

# comparison of extents
raster::extent(slope)
> class       : Extent 
xmin        : 794599.1 
xmax        : 798208.6 
ymin        : 8931775 
ymax        : 8935384 

raster::extent(slp.sBuf.RQGIS)
> class       : Extent 
xmin        : 794599.1 
xmax        : 798239.4 
ymin        : 8931744 
ymax        : 8935384 

raster::extent(slp.sBuf.RSAGA)
> class       : Extent 
xmin        : 794599.1 
xmax        : 798208.6 
ymin        : 8931775 
ymax        : 8935384 
```

Btw: I have the question how you write out NA-data in raster files?

**Comment by pat-s** [comment]
Looks interesting, thanks for contributing @raff-k! 

PS: A small comment regarding the formatting of code: To display many code lines, simply wrap those in three backticks at the start and end of the code (see the formatted example of your first post). 
Single backticks should be used for inline-code only :)
Also, it would be nice if you could line break your code after a margin of 80 or similar so that it fits into the Github editor without having to move to the right. Thanks!

**Comment by raff-k** [comment]
Hello. I further investigate in `saga:gridbuffer`  and assume that depending on the QGIS version there is probably a bug in QGIS and SAGA:
- in **QGIS 2.14**  `saga:gridbuffer`  is running. At first the algo exports the `.tif` as `.sgrd` with `io_gdal` and then computes the grid buffer. Interestingly, the grid system is changing from `30.85; 118x 118y; 794588.025x 8931769.125y` to `30.85; 119x 119y; 794588.025x 8931738.275000y`. So, one row and column more as before.

- in **QGIS 2.18**  `saga:gridbuffer`  is generally not working. One get the error message `Unknown option 'DIST'`. This occured due to the changing in DISTANCE parameter. If you execute`RSAGA::rsaga.get.usage(lib="grid_tools", module = 8, env = env.rsaga)` with different SAGA versions, i.e. 2.1.2 and 2.3.2, you can see that `DIST` has changed to `DISTANCE`. It seems that the processing toolbox of QGIS is still hard coded. (... but also funny that SAGA changed parameter names)

- another interesting behaviour I had on my machine was that there seems to be a difference between `writeRaster` and `writeGDAL` in writing out files as `.sgrd` or `.sdat`. When I imported the different written files in SAGA 2.1.2 the extent of the GDAL file was `119x 119y` and of the writeRaster file `118x 118y` (which was the original input). However, in SAGA 2.3.2 this behaviour seems to be gone (but in this version `saga:gridbuffer` is not working through QGIS ...).

![saga gis](https://user-images.githubusercontent.com/26696813/34219216-c8825dbe-e5b0-11e7-99b7-d97fd85b67e4.JPG)

**Comment by pat-s** [comment]
When its a QGIS/SAGA bug, I'm sure that the QGIS dev guys would highly appreciate if you could provide a reprex at their [issue tracker](https://issues.qgis.org/projects/qgis/issues) :smile:

**Comment by raff-k** [comment]
Btw, currently I discovered that SAGA GIS does NOT support unequal xy cell sizes as resolution. It automatically resamples to equally sized cells. Which means, that such a raster input in RQGIS will provide a non-matching raster output (in terms of raster::compareRaster(...)). Maybe you should add a warning message if SAGA is used and resolution cells are unequal...

```r
if(!require("pacman")){install.packages("pacman")}
pacman::p_load("RQGIS", "raster")

# init RQGIS
RQGIS::open_app()

# load and create data
dem <- RQGIS::dem
dem.resample <- raster::raster(x = raster::extent(dem), res = c(31, 30), 
                               crs = raster::crs(dem))

# resampling to unequal cell sizes
dem.resample <- raster::resample(x = dem, y = dem.resample)
raster::plot(dem.resample)


# run any RQGIS-processing using SAGA GIS
slope.test <- RQGIS::run_qgis(alg = "saga:slopeaspectcurvature", load_output = TRUE,
         show_output_paths = TRUE, NA_flag = -99999, params = list(
           ELEVATION = dem.resample, 
           SLOPE = file.path(tempdir(), "test_slope.tif")))


raster::res(slope.test) # [1] 30 30
raster::compareRaster(x = dem.resample, y = slope.test) 
# Error in raster::compareRaster(x = dem.resample, y = slope.test) : 
#   different extent


# ... now the original DEM
slope.orig <- RQGIS::run_qgis(alg = "saga:slopeaspectcurvature", load_output = TRUE,
                              show_output_paths = TRUE, NA_flag = -99999, params = list(
                                ELEVATION = dem, 
                                SLOPE = file.path(tempdir(), "test_slope_orig.tif")))

raster::res(x = slope.orig) # [1] 30.85 30.85
raster::compareRaster(x = dem, y = slope.orig) # [1] TRUE
```
