### ISSUE TITLE
grass7:i.segment does not finish

### ISSUE THREAD

**Issue by raff-k** [jannes-m/RQGIS#90]
Dear RQGIS-Team,

I would like to perform a segmentation using RQGIS instead of rgrass7. However, the process is running and never seems to finish. As comparison I computed the same task using rgrass7 and the same algorithm- the process is executed there in 1.5 minutes!
The raster I use is very large (93 535 000 elements) but most of the values are NA.  I uploaded the file, so that you could reproduce the issue: [file](https://github.com/raff-k/Lslide/raw/master/data/InputSegmentation.Rda). 
The `grass7:i.segment` algorithm is generally working, testing the `RQGIS::dem`. I speculate, that mabye by writing out the NA data, something happens, so that all values are included in the GRASS segmentation (then it will probably run multiple hours).
Beside, computing `grass7:i.group` I got the error message, that at least two input raster must be given. However, taking a look on the [GRASS GIS manual](https://grass.osgeo.org/grass72/manuals/i.group.html), one input should be valid as well.

```r
# load libraries
library(rgrass7, RQGIS, sp, raster)

# load data
setwd("E:/GrassData")
load("InputSegmentation.Rda")

# or directly via source
githubURL <- "https://github.com/raff-k/Lslide/raw/master/data/InputSegmentation.Rda"
load(url(githubURL))

input.segmentation.SGDF <- as(input.segmentation, "SpatialGridDataFrame")

### RGRASS7 ---------------
# init grass project
rgrass7::initGRASS("C:/OSGeo4W64/apps/grass/grass-7.2.2", home = tempdir(), 
                   SG = as(input.segmentation, "SpatialGrid"), override=TRUE)

# load data into GRASS
rgrass7::writeRAST(input.segmentation.SGDF, "SegmentationGrass", 
                   zcol="layer", useGDAL = TRUE)


# perform segmentation
rgrass7::execGRASS("i.group", flags = c("quiet"), 
                   Sys_show.output.on.console = FALSE, 
                   parameters = list(group = "SegmentationGroup", 
                                     input = "SegmentationGrass"))


processTmeStart.RGRASS7 <- proc.time()

rgrass7::execGRASS("i.segment", group = "SegmentationGroup", 
                   output = "SegmentsOut", threshold = 0.02)

cat(paste0("------ Run of RGRASS7 Segmentation: " , 
           (proc.time() - processTmeStart.RGRASS7)["elapsed"][[1]]/60, 
           " Minutes ------"))
# ------ Run of RGRASS7 Segmentation: 1.42583333333334 Minutes ------


# check output
segmentation.rgrass7 <- rgrass7::readRAST("SegmentsOut")
segmentation.rgrass7.r <- raster::raster(segmentation.rgrass7)
plot(segmentation.rgrass7.r) # alright



### RQGIS ---------------
RQGIS::open_app()

# I stopped this process after 1 hour!
processTmeStart.RQGIS <- proc.time()

segmentation.RQGIS <- RQGIS::run_qgis(alg = "grass7:i.segment", 
                                      input = input.segmentation, threshold = "0.02",
                                      output = "tmpGrassSegmt.tif", 
                                      load_output = TRUE, show_output_paths = TRUE)

cat(paste0("------ Run of RQGIS Segmentation: " , 
           (proc.time() - processTmeStart.RQGIS)["elapsed"][[1]]/60, 
           " Minutes ------"))


# ... however, using RQGIS::DEM generally works fine and fast
segmentation.RQGIS.DEM <-  RQGIS::run_qgis(alg = "grass7:i.segment", 
                                           input = RQGIS::dem, threshold = "0.02",
                                           output = "tmpGrassSegmtDEM.tif", 
                                           load_output = TRUE, 
                                           show_output_paths = TRUE)

sp::spplot(segmentation.RQGIS.DEM) # alright

```

**Comment by jannes-m** [comment]
The first thing you shouldn't do is, is to you use an R spatial object as input (`input.segmentation`) instead use the path to the file stored on disk. Secondly, set the `load_output` parameter to `FALSE`. Give it another try. Still, it's strange that it takes so long. However, it seems to be more a QGIS than a RQGIS problem, but you can add the problem to https://github.com/jannes-m/RQGIS/blob/master/known_issues.Rmd or even better report it directly to QGIS. Before doing so, try to interactively run this algorithm in the QGIS GUI just to check if the same problem arises.

**Comment by raff-k** [comment]
Thanks for the reply :)
`input.segmentation` is a `RasterLayer`, I only convert it to `Spatial` for `rgrass7`.  However, setting `load_output` to `FALSE` and using the path do not solve the problem, still running (in the task manager I can see that Grass Gis process is running).
Besides, using the python console inside QGIS 2.18.14 I could not find `grass7:i.segment`, and it was also not listed in `processing.alglist()`... and^^ I cannot use the processing toolbox due to the hard coded [bug](https://issues.qgis.org/issues/16110)...

**Comment by pat-s** [comment]
> Besides, using the python console inside QGIS 2.18.14 I could not find grass7:i.segment, and it was also not listed in processing.alglist()... and^^ I cannot use the processing toolbox due to the hard coded bug...

Your link points to a Linux problem but you are using Windows, correct?
On my Linux machine(s) everything runs fine. Also on my Windows Box. 

```r
library(RQGIS)
find_algorithms("grass7:i.segment")
Assuming that your root path is '/usr'!
[1] "i.segment - Identifies segments (objects) from imagery data.--->grass7:i.segment"
```

**Comment by jannes-m** [comment]
Yeah, I know that it is a raster layer, and `run_qgis()` simply saves this input raster to `tempdir()` which is rather time-consuming given that one can already find it somewhere stored on disk.

If one cannot access the algorithm via the GUI, then one can file a bug report without having run the GUI 😄

**Comment by raff-k** [comment]
`find_algorithms("grass7:i.segment")` works, also ...
```r
RQGIS::run_qgis(alg = "grass7:i.segment", input = RQGIS::dem, threshold = "0.02",
                                       output = "tmpGrassSegmtDEM.tif", load_output = TRUE, show_output_paths = TRUE)
```

works. But not for my input :-/ 
I just have no idea how to run the `grass7:i.segment`-algorithm inside QGIS, because I cannot find it (and I nearly never used QGIS before ;-) )

**Comment by pat-s** [comment]
I can reproduce your issue, QGIS also runs infinite with max. CPU for me. 
Seems like an QGIS issue and you can add it to the list as @jannes-m  already said. 

PS: Please try to format your code on Github in the future so that it does not exceed an margin of 80. Thanks!
