### ISSUE TITLE
Error in "grass7:r.neighbors" with method = "6" - sum using raster with NA-values

### ISSUE THREAD

**Issue by raff-k** [jannes-m/RQGIS#92]
Dear RQGIS-team,
I am trying to do a focal statistic analysis using `grass7:r.neighbors` with the method _sum ("6")_, but I got the following error:

> Error in FUN(X[[i]], ...) : 
> Unfortunately, QGIS did not produce: C:/Users/USER/AppData/Local/Temp/
> Rtmp0eYKS8/DEM_NA_NB_SUM.tif

As input I use a raster containing NA-values. The function works using _sum_ with the standard `RQGIS::dem` as input, **and** the function works with any other method using the NA-input. That solely _sum_ is not working (the method I want to use) I found so strange, that I tested the following code also on a second computer, but with the same result...

I have a windows machine 64bit and use QGIS 2.18.14 with GRASS GIS 7.2.2.
... maybe this is again a QGIS-issue(?).

```r
# load packages
library(RQGIS, raster)
set_env(dev = TRUE, new = TRUE)
open_app()

# doing focal statistics with GRASS GIS using standard method (average)
dem.NB <- RQGIS::run_qgis(alg = "grass7:r.neighbors", input = RQGIS::dem,
                output = "DEM_NB.tif", load_output = TRUE)

# ... now, testing sum or method = "6"
dem.NB.SUM <- RQGIS::run_qgis(alg = "grass7:r.neighbors", input = RQGIS::dem,
                          method = "6", output = "DEM_NB_SUM.tif", load_output = TRUE)

### now, the funny thing
# create a raster with NAs
dem.NA <- raster::calc(RQGIS::dem, function(x){ifelse(x >= 350, NA, x)})

# ... using standard method
dem.NA.NB <- RQGIS::run_qgis(alg = "grass7:r.neighbors", input = dem.NA,
                        output = "DEM_NA_NB.tif", load_output = TRUE)


# ... now, testing sum or method = "6"
dem.NA.NB.SUM <- RQGIS::run_qgis(alg = "grass7:r.neighbors", input = dem.NA,
                              method = "6", output = "DEM_NA_NB_SUM.tif", load_output = TRUE)

>Error in FUN(X[[i]], ...) : 
>Unfortunately, QGIS did not produce: 
>C:/Users/rAVer/AppData/Local/Temp/Rtmp0eYKS8/DEM_NA_NB_SUM.tif

# ... now, testing any other method, i.e. 4
dem.NA.NB.4 <- RQGIS::run_qgis(alg = "grass7:r.neighbors", input = dem.NA,
                            method = "4", output = "DEM_NA_NB_4.tif", load_output = TRUE)

```

**Comment by jannes-m** [comment]
Maybe https://github.com/jannes-m/RQGIS/commit/9e74a4a76d305008002cb79682a8bd771e508bea also solves this issue, pls check.

**Comment by raff-k** [comment]
`"grass7:r.neighbors"` with `method = "6" or "sum"` is working now. Thank you, @jannes-m , for bug fixing :-)

**Comment by jannes-m** [comment]
Good to hear! Happy geoprocessing! And thanks for your input!
