### ISSUE TITLE
Producing outputs in loops stops after certain iterations

### ISSUE THREAD

**Issue by danceb** [jannes-m/RQGIS#96]
If I'm using RQGIS for producing a big amount of output files using loops, the procedure stops after certain iterations and results in the error:
`Error in FUN(X[[i]], ...) : Unfortunately, QGIS did not produce (some file.path)`

It seems like it caches the output files somehow until the cache is full. This happens with for and lapply loops.

Data:
[sampledata.zip](https://github.com/jannes-m/RQGIS/files/1751329/sampledata.zip)

What I am trying to do here is to cut many building polygons by crossing lines. The used SAGA function works only correctly if I am using only one line per polygon to cut with. So I have to iterate through the polygons and furthermore through the cutting lines.

Thanks for any help.

```r
library(RQGIS)
library(sf)

set_env("C:/Program Files/QGIS 2.18")

params <- get_args_man(alg = "saga:polygonlineintersection")

geb.sel.block.tmp <- vector(mode = "list", length = nrow(geb.sel.block))

names(geb.sel.block.tmp) <- as.character(geb.sel.block$oid)

geb.sel.block.tmp <- lapply(seq(1:length(geb.sel.block.tmp)), function(numb) {
  params$POLYGONS <- subset(geb.sel.block, oid == names(geb.sel.block.tmp)[numb])
  geb.linien.sub <- subset(geb.linien, geb.oid == names(geb.sel.block.tmp)[numb])
  for (linie in seq(1:nrow(geb.linien.sub))) {
    params$LINES <- geb.linien.sub[linie,]
    params$INTERSECT <- file.path(tempdir(), 
                                  paste0("geb_", names(geb.sel.block.tmp)[numb], linie, ".shp"))
    tmp <- run_qgis(alg = "saga:polygonlineintersection",
                    params = params,
                    load_output = TRUE)
    params$POLYGONS <- tmp
  }
  geb.sel.block.tmp[numb] <- list(params$POLYGONS)
})

```

After that I have to restart RStudio to produce RQGIS-Output again.

**Comment by jannes-m** [comment]
#74 #77 #82

**Comment by jannes-m** [comment]
Using the unlock-branch should solve your problem:
```r
devtools::install_github("jannes-m/RQGIS", ref = "unlock")
```

**Comment by danceb** [comment]
Unfortunately it doesn't. The problem is not the deleting of the temp files as in #82 (this works) and the result is exact the one I have expected (#74, #77). 
Using the unlock-branch instead of the master RQGIS doesn't change the problem: The loop stops after 21 iterations.
BTW I have updated the code in the first comment to save the results in a list and uploaded respective sample data.

**Comment by jannes-m** [comment]
I am sorry but I can't reproduce your error. Using your code and sample data everything works fine.

Maybe you have to clean up your TEMP folder (and yes I have been thinking about including a function to do so automatically). On the other hand, nothing stops you to write your output to another location, e.g., `"D:/intersection"` intead of `tempdir()`.

**Comment by danceb** [comment]
The location doesn't matter. The best errors are the ones which could not be reproduced...
Ok, so I have to look for another function/tool to do this. I think, the issue can be closed now. Thanks, anyway.

**Comment by jannes-m** [comment]
Have you tried to find out if there is something wrong with the input at the iteration where RQGIS does not produce an output (would apply if you use other data than the provided sample data).

**Comment by danceb** [comment]
I've created some random polygons and lines to test this: [sampledata2.zip](https://github.com/jannes-m/RQGIS/files/1757743/sampledata2.zip)
The same execution error here.

more general code for the new sample data:
```r
library(RQGIS)
library(sf)

set_env("C:/Program Files/QGIS 2.18")

params <- get_args_man(alg = "saga:polygonlineintersection")

polys.tmp <- vector(mode = "list", length = nrow(polys))

names(polys.tmp) <- as.character(polys$id)

polys.tmp <- lapply(seq(1:length(polys.tmp)), function(numb) {
  params$POLYGONS <- subset(polys, id == names(polys.tmp)[numb])
  lines.sub <- subset(lines, id == names(polys.tmp)[numb])
  for (linie in seq(1:nrow(lines.sub))) {
    params$LINES <- lines.sub[linie,]
    params$INTERSECT <- file.path(tempdir(), 
                                  paste0("geb_", names(polys.tmp)[numb], linie, ".shp"))
    tmp <- run_qgis(alg = "saga:polygonlineintersection",
                    params = params,
                    load_output = TRUE)
    params$POLYGONS <- tmp
  }
  polys.tmp[numb] <- list(params$POLYGONS)
})
```

I have tried the procedure with another function. Here small polygons should be unioned with larger polygons [sampledata_union.zip](https://github.com/jannes-m/RQGIS/files/1757784/sampledata_union.zip):

```r
params <- get_args_man(alg = "saga:union")

polys.tmp <- vector(mode = "list", length = nrow(polys))

names(polys.tmp) <- as.character(polys$id)

polys.tmp <- lapply(seq(1:length(polys.tmp)), function(numb) {
  params$A <- subset(polys, id == names(polys.tmp)[numb])
  polys.to.union.sub <- subset(polys.to.union, id == names(polys.tmp)[numb])
  for (linie in seq(1:nrow(polys.to.union.sub))) {
    params$B <- polys.to.union.sub[linie,]
    params$RESULT <- file.path(tempdir(), 
                                  paste0("geb_", names(polys.tmp)[numb], linie, ".shp"))
    tmp <- run_qgis(alg = "saga:union",
                    params = params,
                    load_output = TRUE)
    params$A <- tmp
  }
  polys.tmp[numb] <- list(params$A)
})
```

As with the other function the loop aborts after certain iterations.

The solution for my specific problem was (sadly for RQGIS) simply not to use it. Cutting polygons with lines works much better (and really faster) with the `st_split` function out of the `lwgeom` package.
However there might be the moment, to using qgis functions within a loop. Would be interesting, if there are others with the same problem than me.

**Comment by pat-s** [comment]
Wondering if using QGIS3 (just released yesterday, not compatible yet withj RQGIS) might have any effect on it.

**Comment by gisma** [comment]
Could reproduce the execution error as described by @danceb  on a win10  test system running QGIS 2.18.

However after updating the R packages everything works fine.  Also no problems running the example using linux.

@danceb  btw if you think that using SAGA via QGIS under Windows might be slow and inconvenient, you might consinder to run it directly or just use Linux. A short profiling sourcing your example shows: 

Code | File | Memory (MB) | Time (ms)
-- | -- | -- | --
**Linux Ubuntu Mint 18.1**
lapply |   -23.8    | 23.6 | 3240 |  
get_args_man    | 0    | 2.5 | 3440 |  
library |    -36.7   | 39.8 | 1180 |  
**Win 10 same system**
lapply |    -34.0  |   38.6 | 51800 |  
get_args_man |    -2.9  |  2.3 | 2940 |  
library |    -32.7    | 38.9 | 1640 |  

cheers Chris
